# Generated by Django 2.2.10 on 2021-02-25 17:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True, verbose_name='路径')),
                ('text', models.CharField(max_length=254, verbose_name='文本')),
                ('type', models.CharField(choices=[('branch', '分支'), ('alarm', '报警'), ('screen', '聚合图形')], default='branch', max_length=50, verbose_name='类型')),
                ('space', models.CharField(choices=[('user', '用户'), ('organization', '组织')], max_length=50, verbose_name='空间')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='设置')),
                ('owners', models.ManyToManyField(blank=True, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewers', to=settings.AUTH_USER_MODEL, verbose_name='观众')),
            ],
            options={
                'verbose_name': 'TreeNode',
            },
        ),
    ]
